"""empty message

Revision ID: 7f281f43220f
Revises: 
Create Date: 2020-06-16 15:03:00.122405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f281f43220f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint('movies_actor_id_fkey', 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'actors', ['actor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key('movies_actor_id_fkey', 'movies', 'actors', ['actor_id'], ['id'], ondelete='CASCADE')
    op.alter_column('actors', 'gender',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('actors', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
